- name: Set SGE conf facts for CentOS
  set_fact:
    SGE_ROOT: "/usr/share/gridengine"
  when: ansible_os_family == "RedHat"

- name: Set SGE conf facts for CentOS >=7
  set_fact:
    SGE_ROOT: "/opt/sge"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

# CLUES SGE configuration
- ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.sge
  notify: restart cluesd
- copy: src=/etc/clues2/conf.d/plugin-sge.cfg-example dest=/etc/clues2/conf.d/plugin-sge.cfg force=no
  notify: restart cluesd
- copy: src=/etc/clues2/conf.d/wrapper-sge.cfg-example dest=/etc/clues2/conf.d/wrapper-sge.cfg force=no
  notify: restart cluesd
- lineinfile: dest={{SGE_ROOT}}/default/common/sge_request regexp='^-jsv' line="-jsv /usr/local/bin/clues-sge-wrapper" create=yes mode=644
  notify: restart cluesd
- lineinfile: dest=/etc/profile.d/sge_vars.sh regexp='SGE_JSV_TIMEOUT' line="export SGE_JSV_TIMEOUT=600" create=yes mode=755
  notify: restart cluesd
- ini_file: dest=/etc/clues2/conf.d/plugin-sge.cfg section=SGE option=SGE_ROOT value="/usr/share/gridengine"
  when: ansible_os_family == "RedHat"
  notify: restart cluesd

- ini_file: dest=/etc/clues2/conf.d/plugin-sge.cfg section={{ item.section }} option={{ item.option }} value="{{ item.value }}"
  with_items:
    - { section: 'SGE', option: 'SGE_QHOST_COMMAND', value: '/opt/sge/bin/lx-amd64/qhost' }
    - { section: 'SGE', option: 'SGE_QSTAT_COMMAND', value: '/opt/sge/bin/lx-amd64/qstat' }
    - { section: 'SGE', option: 'SGE_QCONF_COMMAND', value: '/opt/sge/bin/lx-amd64/qconf' }
    - { section: 'SGE', option: 'SGE_ROOT', value: '/opt/sge' }
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  notify: restart cluesd

- ini_file: dest=/etc/clues2/conf.d/wrapper-sge.cfg section={{ item.section }} option={{ item.option }} value="{{ item.value }}"
  with_items:
    - { section: 'SGE', option: 'SGE_QHOST_COMMAND', value: '/opt/sge/bin/lx-amd64/qhost' }
    - { section: 'SGE', option: 'SGE_QSTAT_COMMAND', value: '/opt/sge/bin/lx-amd64/qstat' }
    - { section: 'SGE', option: 'SGE_QCONF_COMMAND', value: '/opt/sge/bin/lx-amd64/qconf' }
    - { section: 'SGE', option: 'SGE_ROOT', value: '/opt/sge' }
  notify: restart cluesd
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- lineinfile: dest={{SGE_ROOT}}/default/common/sge_request regexp='^-jsv' line="-jsv /usr/bin/clues-sge-wrapper" create=yes mode=644
  notify: restart cluesd
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

